### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by hyperioxx** [Frontman-Labs/frontman#14]
The logging in Frontman could be improved to provide more comprehensive information about its operations. This could include logging of request and response details, as well as logging of errors and other important events.

Proposed Solution:

- Add more detailed logging statements throughout the codebase to provide more information about Frontman's operations.

- Add a mechanism to enable/disable debug level logging to reduce noise in production environments.

- Use a structured logging framework such as Zap or Logrus to make it easier to search, filter and analyze logs.

- <s> Add the ability to send logs to an external logging service such as Elasticsearch or Splunk. </s>  (removed due to a a good suggestion by @CCOLLOT )

- Add support for custom log formats to allow users to tailor the format to their specific requirements.

Expected Outcome: Improved logging will make it easier for developers and operations teams to diagnose issues and monitor the health of the Frontman instance.

**Comment by certino-simonchapman** [comment]
was thinking, would be nice to be able to bolster support for some of those big monitoring players out there.. like splunk (mentioned) and datadog..

I raised the plugin support item, and wonder.. is there the risk of these overlapping a bit? whats your thoughts on whether one should supersede the other. I do feel as though maybe the events for monitors should be a bit more.. perhaps engrained into the inner workings where plugins wouldn't have access, to give a common layer. But maybe the design of plugins perhaps have an interface into this very monitoring system?

Keen to hear your thoughts :)

**Comment by CCOLLOT** [comment]
Hey, I think sending logs synchronously to an external log database is not a good idea (performance issues). 
The standard way of handling logs is usually to scrape the app's log files (or stdout  log files for containers/pods) using a tool like `promtail`, `filebeat`, `fluentd`etc... 
I think it should be removed from this issue.

**Comment by CCOLLOT** [comment]
So I guess I can help with this. Would a Logger interface wrapping basic `zap.Logger` functionalities suit you? 

```golang
type Logger interface {
	Debug(args ...interface{})
	Debugf(format string, args ...interface{})
	Info(args ...interface{})
	Infof(format string, args ...interface{})
	Warn(args ...interface{})
	Warnf(format string, args ...interface{})
	Error(args ...interface{})
	Errorf(format string, args ...interface{})
	WithFields(level logLevel, msg string, fields ...Field)
}
```

**Comment by hyperioxx** [comment]
@CCOLLOT Yeah the interface looks good !
