### ISSUE TITLE
Phase 2 - Implement support for basic authentication using username and password

### ISSUE THREAD

**Issue by hyperioxx** [Frontman-Labs/frontman#20]
Currently, Frontman does not support basic authentication using username and password. This feature is important for securing access to backend services that do not have their own authentication mechanisms. Implementing support for basic authentication will allow users to define credentials for accessing backend services.

#### Proposed Solution: 
The proposed solution is to add a new field for username and password in the backend service struct. These credentials can be used to add the basic authentication header to requests made to the backend service. The username and password can be read from environment variables or a configuration file. Additionally, we can add a flag to specify the location of the configuration file or environment variables.

**Comment by nhaydel** [comment]
I plan on taking this issue next since it aligns with my previous Auth work. Just so I don't replicate the issue again, what was the issue with the jwt Auth implementation?

**Comment by hyperioxx** [comment]
It was something on the lines of  calling AuthValidator and it would return a nil pointer if the backend didn’t have auth setup

**Comment by nhaydel** [comment]
> It was something on the lines of  calling AuthValidator and it would return a nil pointer if the backend didn’t have auth setup 

Weird. I tested that, but my approach changes in between tests. Thanks for cleaning that up for me!
