### ISSUE TITLE
Move to supported HTTP router library

### ISSUE THREAD

**Issue by CCOLLOT** [Frontman-Labs/frontman#67]
[gorilla/mux ](https://github.com/gorilla/mux) is not maintained anymore. 
Moving to a supported HTTP router library should be a top priority (especially for young projects) to avoid future issues (mainly security issues).

Popular alternatives include (non-exhaustive):
+ [Gin](https://github.com/gin-gonic/gin)
+ [Echo](https://github.com/labstack/echo)
+ [Chi](https://github.com/go-chi/chi)

Side Note: This is good opportunity to introduce a proper `Server` struct we could attach functions to (`server.Create()`, `server.Start()`, `server.Stop()`...). It would also enable injecting other useful elements such as the `Logger`, as well as properly mocking the server (if needed) during tests.

**Comment by nhaydel** [comment]
I like this idea. I'm not too biased, but in the past I've used chi and really liked it

**Comment by hyperioxx** [comment]
Crazy idea! but what about rolling our own ? Thoughts ?

**Comment by simonchapman1986** [comment]
Interesting idea @hyperioxx … well, when we consider this IS a router, as in, that’s the very purpose of a gateway.. there is strength in your idea here. 

We have some very specific needs when taking something from point A to point B.. and when we consider the idea of plugins that we have and the ability to transform things along the way. This might actually be a bloody good idea @hyperioxx … I’m with you, fuck it, should roll our own 🔥

**Comment by hyperioxx** [comment]
@Frontman-Labs/contributor @Frontman-Labs/core-team could you just take a look at this PR https://github.com/Frontman-Labs/frontman/pull/68 just the idea of moving forward

**Comment by hyperioxx** [comment]
https://github.com/Frontman-Labs/frontman/pull/68 has been merged and a new ticket has been created for removing mux from the management api
