### ISSUE TITLE
Remove Gorilla's Dependency from Management API due to Lack of Maintenance

### ISSUE THREAD

**Issue by hyperioxx** [Frontman-Labs/frontman#73]
The Management API currently relies on the Gorilla library, which has not been maintained for some time. As a result, I believe it's necessary to remove this dependency to ensure the long-term stability and security of the Management API.

Although this change may not be urgent, it's important to address it sooner rather than later to avoid potential issues down the road. Additionally, by removing the dependency on Gorilla, we can potentially improve the performance and maintainability of the Management API.

**Comment by amityahav** [comment]
@hyperioxx  what do we think about Gin framework?

**Comment by amityahav** [comment]
@hyperioxx there's a pr for that already
