### ISSUE TITLE
move buildRoutes function call from gateway handler

### ISSUE THREAD

**Issue by amityahav** [Frontman-Labs/frontman#80]
[this](https://github.com/Frontman-Labs/frontman/blob/main/gateway/gateway.go#L38) should be moved away and not be triggered each time a request is processed for better performance and because this prefix tree doesn't change unless there has been a modification in the service registry.

**Comment by amityahav** [comment]
@hyperioxx faced some annoying issue with this one. My idea was to move this function to be called once the service starts and each time a modification is made to the registry. Hence I would need a ref of the tree both in registry struct and gateway struct. So now the problem is that I get cyclic imports because in the service package I import gateway package because of the routing trie, which has backendService in its members so service package is imported but service package has gateway .. cycle .
I would love your opinion on this

**Comment by hyperioxx** [comment]
@amityahav If that's the case maybe we restructure and try and better align the modules
